[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "TheWordWizard"
version = "0.1.0"
description = "A simple text analyzer"
authors = [ 
    {name = "Evy de Bruine", email = "evydebruine@gmail.com"},
]
dependencies = ["nltk", "matplotlib", "seaborn", "fpdf"]
